using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace PMDOAddPokémon
{
    class PokéDex
    {

        public static readonly string[] PokeFromNum = new string[]
        {
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch’d",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-oh",
"Celebi",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Taillow",
"Swellow",
"Wingull",
"Pelipper",
"Ralts",
"Kirlia",
"Gardevoir",
"Surskit",
"Masquerain",
"Shroomish",
"Breloom",
"Slakoth",
"Vigoroth",
"Slaking",
"Nincada",
"Ninjask",
"Shedinja",
"Whismur",
"Loudred",
"Exploud",
"Makuhita",
"Hariyama",
"Azurill",
"Nosepass",
"Skitty",
"Delcatty",
"Sableye",
"Mawile",
"Aron",
"Lairon",
"Aggron",
"Meditite",
"Medicham",
"Electrike",
"Manectric",
"Plusle",
"Minun",
"Volbeat",
"Illumise",
"Roselia",
"Gulpin",
"Swalot",
"Carvanha",
"Sharpedo",
"Wailmer",
"Wailord",
"Numel",
"Camerupt",
"Torkoal",
"Spoink",
"Grumpig",
"Spinda",
"Trapinch",
"Vibrava",
"Flygon",
"Cacnea",
"Cacturne",
"Swablu",
"Altaria",
"Zangoose",
"Seviper",
"Lunatone",
"Solrock",
"Barboach",
"Whiscash",
"Corphish",
"Crawdaunt",
"Baltoy",
"Claydol",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Feebas",
"Milotic",
"Castform",
"Kecleon",
"Shuppet",
"Banette",
"Duskull",
"Dusclops",
"Tropius",
"Chimecho",
"Absol",
"Wynaut",
"Snorunt",
"Glalie",
"Spheal",
"Sealeo",
"Walrein",
"Clampearl",
"Huntail",
"Gorebyss",
"Relicanth",
"Luvdisc",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Latias",
"Latios",
"Kyogre",
"Groudon",
"Rayquaza",
"Jirachi",
"Deoxys",
"Turtwig",
"Grotle",
"Torterra",
"Chimchar",
"Monferno",
"Infernape",
"Piplup",
"Prinplup",
"Empoleon",
"Starly",
"Staravia",
"Staraptor",
"Bidoof",
"Bibarel",
"Kricketot",
"Kricketune",
"Shinx",
"Luxio",
"Luxray",
"Budew",
"Roserade",
"Cranidos",
"Rampardos",
"Shieldon",
"Bastiodon",
"Burmy",
"Wormadam",
"Mothim",
"Combee",
"Vespiquen",
"Pachirisu",
"Buizel",
"Floatzel",
"Cherubi",
"Cherrim",
"Shellos ",
"Gastrodon",
"Ambipom",
"Drifloon",
"Drifblim",
"Buneary",
"Lopunny",
"Mismagius",
"Honchkrow",
"Glameow",
"Purugly",
"Chingling",
"Stunky",
"Skuntank",
"Bronzor",
"Bronzong",
"Bonsly",
"Mime Jr.",
"Happiny",
"Chatot",
"Spiritomb",
"Gible",
"Gabite",
"Garchomp",
"Munchlax",
"Riolu",
"Lucario",
"Hippopotas",
"Hippowdon",
"Skorupi",
"Drapion",
"Croagunk",
"Toxicroak",
"Carnivine",
"Finneon",
"Lumineon",
"Mantyke",
"Snover",
"Abomasnow",
"Weavile",
"Magnezone",
"Lickilicky",
"Rhyperior",
"Tangrowth",
"Electivire",
"Magmortar",
"Togekiss",
"Yanmega",
"Leafeon",
"Glaceon",
"Gliscor",
"Mamoswine",
"Porygon-Z",
"Gallade",
"Probopass",
"Dusknoir",
"Froslass",
"Rotom",
"Uxie",
"Mesprit",
"Azelf",
"Dialga",
"Palkia",
"Heatran",
"Regigigas",
"Giratina",
"Cresselia",
"Phione",
"Manaphy ",
"Darkrai",
"Shaymin",
"Arceus",
"Victini",
"Snivy",
"Servine",
"Serperior",
"Tepig",
"Pignite",
"Emboar",
"Oshawott",
"Dewott",
"Samurott",
"Patrat",
"Watchog",
"Lillipup",
"Herdier",
"Stoutland",
"Purrloin",
"Liepard",
"Pansage",
"Simisage",
"Pansear",
"Simisear",
"Panpour",
"Simipour",
"Munna",
"Musharna",
"Pidove",
"Tranquill",
"Unfezant",
"Blitzle",
"Zebstrika",
"Roggenrola",
"Boldore",
"Gigalith",
"Woobat",
"Swoobat",
"Drilbur",
"Excadrill",
"Audino",
"Timburr",
"Gurdurr",
"Conkeldurr",
"Tympole",
"Palpitoad",
"Seismitoad",
"Throh",
"Sawk",
"Sewaddle",
"Swadloon",
"Leavanny",
"Venipede",
"Whirlipede",
"Scolipede",
"Cottonee",
"Whimsicott",
"Petilil",
"Lilligant",
"Basculin",
"Sandile",
"Krokorok",
"Krookodile",
"Darumaka",
"Darmanitan",
"Maractus",
"Dwebble",
"Crustle",
"Scraggy",
"Scrafty",
"Sigilyph",
"Yamask",
"Cofagrigus",
"Tirtouga",
"Carracosta",
"Archen",
"Archeops",
"Trubbish",
"Garbodor",
"Zorua",
"Zoroark",
"Minccino",
"Cinccino",
"Gothita",
"Gothorita",
"Gothitelle",
"Solosis",
"Duosion",
"Reuniclus",
"Ducklett",
"Swanna",
"Vanillite",
"Vanillish",
"Vanilluxe",
"Deerling",
"Sawsbuck",
"Emolga",
"Karrablast",
"Escavalier",
"Foongus",
"Amoonguss",
"Frillish",
"Jellicent",
"Alomomola",
"Joltik",
"Galvantula",
"Ferroseed",
"Ferrothorn",
"Klink",
"Klang",
"Klinklang",
"Tynamo",
"Eelektrik",
"Eelektross",
"Elgyem",
"Beheeyem",
"Litwick",
"Lampent",
"Chandelure",
"Axew",
"Fraxure",
"Haxorus",
"Cubchoo",
"Beartic",
"Cryogonal",
"Shelmet",
"Accelgor",
"Stunfisk",
"Mienfoo",
"Mienshao",
"Druddigon",
"Golett",
"Golurk",
"Pawniard",
"Bisharp",
"Bouffalant",
"Rufflet",
"Braviary",
"Vullaby",
"Mandibuzz",
"Heatmor",
"Durant",
"Deino",
"Zweilous",
"Hydreigon",
"Larvesta",
"Volcarona",
"Cobalion",
"Terrakion",
"Virizion",
"Tornadus",
"Thundurus",
"Reshiram",
"Zekrom",
"Landorus",
"Kyurem",
"Keldeo",
"Meloetta",
"Genesect",
"Chespin",
"Quilladin",
"Chesnaught",
"Fennekin",
"Braixen",
"Delphox",
"Froakie",
"Frogadier",
"Greninja",
"Bunnelby",
"Diggersby",
"Fletchling",
"Fletchinder",
"Talonflame",
"Scatterbug",
"Spewpa",
"Vivillon",
"Litleo",
"Pyroar",
"Flabébé",
"Floette",
"Florges",
"Skiddo",
"Gogoat",
"Pancham",
"Pangoro",
"Furfrou",
"Espurr",
"Meowstic",
"Honedge",
"Doublade",
"Aegislash",
"Spritzee",
"Aromatisse",
"Swirlix",
"Slurpuff",
"Inkay",
"Malamar",
"Binacle",
"Barbaracle",
"Skrelp",
"Dragalge",
"Clauncher",
"Clawitzer",
"Helioptile",
"Heliolisk",
"Tyrunt",
"Tyrantrum",
"Amaura",
"Aurorus",
"Sylveon",
"Hawlucha",
"Dedenne",
"Carbink",
"Goomy",
"Sliggoo",
"Goodra",
"Klefki",
"Phantump",
"Trevenant",
"Pumpkaboo",
"Gourgeist",
"Bergmite",
"Avalugg",
"Noibat",
"Noivern",
"Xerneas",
"Yveltal",
"Zygarde",
"Diancie",
"Volcanion",
"Hoopa",
"Rowlet",
"Dartrix",
"Decidueye",
"Litten",
"Torracat",
"Incineroar",
"Popplio",
"Brionne",
"Primarina",
"Pikipek",
"Trumbeak",
"Toucannon",
"Yungoos",
"Gumshoos",
"Grubbin",
"Charjabug",
"Vikavolt",
"Crabrawler",
"Crabominable",
"Oricorio",
"Cutiefly",
"Ribombee",
"Rockruff",
"Lycanroc",
"Wishiwashi",
"Mareanie",
"Toxapex",
"Mudbray",
"Mudsdale",
"Dewpider",
"Araquanid",
"Fomantis",
"Lurantis",
"Morelull",
"Shiinotic",
"Salandit",
"Salazzle",
"Stufful",
"Bewear",
"Bounsweet",
"Steenee",
"Tsareena",
"Comfey",
"Oranguru",
"Passimian",
"Wimpod",
"Golisopod",
"Sandygast",
"Palossand",
"Pyukumuku",
"Type:Null",
"Silvally",
"Minior",
"Komala",
"Turtonator",
"Togedemaru",
"Mimikyu",
"Bruxish",
"Drampa",
"Dhelmise",
"Jangmo-o",
"Hakamo-o",
"Kommo-o",
"Tapu Koko",
"Tapu Lele",
"Tapu Bulu",
"Tapu Fini",
"Cosmog",
"Cosmoem",
"Solgaleo",
"Lunala",
"Nihilgo",
"Buzzwole",
"Pheromosa",
"Xurkitree",
"Celesteela",
"Kartana",
"Guzzlord",
"Necrozma",
"Magearna",
"Marshadow",
"Unknown"
        };

        public enum Moves
        {
            Bullet_Seed = 1,
            Ember = 2,
            Bubble = 3,
            Quick_Attack = 4,
            Thunder_Shock = 5,
            Confusion = 6,
            Mud0Slap = 7,
            Focus_Energy = 8,
            Frenzy_Plant = 9,
            Blast_Burn = 10,
            Hydro_Cannon = 11,
            Hyper_Beam = 12,
            Thunder = 13,
            Psychic = 14,
            Earthquake = 15,
            Slash = 16,
            Fury_Swipes = 17,
            Toxic = 18,
            Bite = 19,
            Heal_Bell = 20,
            Sacred_Fire = 21,
            Spark = 22,
            Focus_Blast = 23,
            Thunderbolt = 24,
            Rock_Tomb = 25,
            Aeroblast = 26,
            Water_Pulse = 27,
            Moonlight = 28,
            Vine_Whip = 29,
            Will0O0Wisp = 30,
            Ice_Shard = 31,
            Flash = 32,
            Thunder_Punch = 33,
            Calm_Mind = 34,
            Sandstorm = 35,
            Absorb = 36,
            Flamethrower = 37,
            Vacuum0Cut = 38,
            Psycho_Boost = 39,
            Roar_of_Time = 40,
            Spacial_Rend = 41,
            Shadow_Force = 42,
            Shadow_Claw = 43,
            Shadow_Sneak = 44,
            Zen_Headbutt = 45,
            Swift = 46,
            Gyro_Ball = 47,
            Flame_Wheel = 48,
            Tri_Attack = 49,
            Pursuit = 50,
            Psywave = 51,
            Swords_Dance = 52,
            Iron_Defense = 53,
            Agility = 54,
            Nasty_Plot = 55,
            Helping_Hand = 56,
            Fire_Fang = 57,
            Thunder_Fang = 58,
            Ice_Fang = 59,
            Powder_Snow = 60,
            Discharge = 61,
            Dragon_Rage = 62,
            Silver_Wind = 63,
            Psycho_Cut = 64,
            Seed_Bomb = 65,
            Heat_Wave = 66,
            Bubble_Beam = 67,
            Body_Slam = 68,
            Soft0Boiled = 69,
            Aura_Sphere = 70,
            Egg_Bomb = 71,
            Double_Slap = 72,
            Bounce = 73,
            Blizzard = 74,
            Dragon_Dance = 75,
            Ominous_Wind = 76,
            Magical_Leaf = 77,
            Cross_Chop = 78,
            Psybeam = 79,
            Withdraw = 80,
            Recycle = 81,
            Close_Combat = 82,
            Power_Gem = 83,
            Sweet_Scent = 84,
            Sheer_Cold = 85,
            Lick = 86,
            Shadow_Ball = 87,
            Gust = 88,
            Icy_Wind = 89,
            Shadow_Punch = 90,
            Dark_Pulse = 91,
            Dragon_Rush = 92,
            Night_Slash = 93,
            Magma_Storm = 94,
            Fire_Blast = 95,
            Lava_Plume = 96,
            Leer = 97,
            Razor_Leaf = 98,
            Grass_Whistle = 99,
            Swagger = 100,
            Mist = 101,
            Ingrain = 102,
            Wood_Hammer = 103,
            Tackle = 104,
            Growl = 105,
            Thunder_Wave = 106,
            Cotton_Spore = 107,
            Charge = 108,
            Signal_Beam = 109,
            Light_Screen = 110,
            Roost = 111,
            Wrap = 112,
            Twister = 113,
            Slam = 114,
            Aqua_Tail = 115,
            Safeguard = 116,
            Wing_Attack = 117,
            Outrage = 118,
            Poison_Sting = 119,
            Pin_Missile = 120,
            Acupressure = 121,
            Knock_Off = 122,
            Scary_Face = 123,
            Toxic_Spikes = 124,
            Poison_Fang = 125,
            Crunch = 126,
            Cross_Poison = 127,
            Minimize = 128,
            Astonish = 129,
            Payback = 130,
            Stockpile = 131,
            Swallow = 132,
            Spit_Up = 133,
            Baton_Pass = 134,
            Explosion = 135,
            Hypnosis = 136,
            Disable = 137,
            Headbutt = 138,
            Poison_Gas = 139,
            Meditate = 140,
            Psych_Up = 141,
            Future_Sight = 142,
            Scratch = 143,
            Sand_Attack = 144,
            Magnitude = 145,
            Dig = 146,
            Sucker_Punch = 147,
            Sand_Tomb = 148,
            Earth_Power = 149,
            Mud_Bomb = 150,
            Fissure = 151,
            Defense_Curl = 152,
            Yawn = 153,
            Glare = 154,
            Rollout = 155,
            Spite = 156,
            Screech = 157,
            Take_Down = 158,
            Ancient_Power = 159,
            Endeavor = 160,
            Flail = 161,
            Night_Shade = 162,
            Bind = 163,
            Gravity = 164,
            Ice_Punch = 165,
            Foresight = 166,
            Confuse_Ray = 167,
            Curse = 168,
            Mean_Look = 169,
            Harden = 170,
            Mud_Sport = 171,
            Water_Gun = 172,
            Metal_Claw = 173,
            Protect = 174,
            Fury_Cutter = 175,
            Rock_Blast = 176,
            Crush_Claw = 177,
            X0Scissor = 178,
            Whirlwind = 179,
            Bug_Buzz = 180,
            Tail_Whip = 181,
            Last_Resort = 182,
            Trump_Card = 183,
            Acid = 184,
            Gastro_Acid = 185,
            Haze = 186,
            Gunk_Shot = 187,
            Low_Kick = 188,
            Shock_Wave = 189,
            Giga_Impact = 190,
            Howl = 191,
            Odor_Sleuth = 192,
            Roar = 193,
            Sonic_Boom = 194,
            Charge_Beam = 195,
            Self0Destruct = 196,
            Magnet_Rise = 197,
            Mirror_Coat = 198,
            Peck = 199,
            Fury_Attack = 200,
            Brine = 201,
            Aqua_Jet = 202,
            Whirlpool = 203,
            Drill_Peck = 204,
            Hydro_Pump = 205,
            Fire_Spin = 206,
            Stomp = 207,
            Extrasensory = 208,
            Morning_Sun = 209,
            Uproar = 210,
            Reflect = 211,
            Leech_Seed = 212,
            Stun_Spore = 213,
            Poison_Powder = 214,
            Sleep_Powder = 215,
            Worry_Seed = 216,
            Natural_Gift = 217,
            Solar_Beam = 218,
            Barrage = 219,
            Leaf_Storm = 220,
            Pound = 221,
            Supersonic = 222,
            Rest = 223,
            Sleep_Talk = 224,
            Hyper_Voice = 225,
            Aerial_Ace = 226,
            Air_Cutter = 227,
            Air_Slash = 228,
            False_Swipe = 229,
            Mirror_Move = 230,
            Assurance = 231,
            Rage = 232,
            Thrash = 233,
            Superpower = 234,
            Attract = 235,
            Rain_Dance = 236,
            Captivate = 237,
            Aqua_Ring = 238,
            U0turn = 239,
            Extreme_Speed = 240,
            Smog = 241,
            Water_Sport = 242,
            Razor_Wind = 243,
            Faint_Attack = 244,
            Dragon_Breath = 245,
            Dragon_Claw = 246,
            Rapid_Spin = 247,
            Bide = 248,
            Spikes = 249,
            Mirror_Shot = 250,
            Double0Edge = 251,
            Zap_Cannon = 252,
            Double_Team = 253,
            Wake0Up_Slap = 254,
            Hail = 255,
            Destiny_Bond = 256,
            Follow_Me = 257,
            Amnesia = 258,
            Me_First = 259,
            Teleport = 260,
            Feint = 261,
            Cosmic_Power = 262,
            Punishment = 263,
            Refresh = 264,
            Recover = 265,
            Perish_Song = 266,
            Judgment = 267,
            Wish = 268,
            Imprison = 269,
            Dream_Eater = 270,
            Nightmare = 271,
            Hidden_Power = 272,
            Muddy_Water = 273,
            Rock_Polish = 274,
            Rock_Throw = 275,
            Stone_Edge = 276,
            Guard_Swap = 277,
            Double_Hit = 278,
            Heal_Block = 279,
            Ice_Beam = 280,
            String_Shot = 281,
            Constrict = 282,
            Leech_Life = 283,
            Spider_Web = 284,
            Poison_Jab = 285,
            Charm = 286,
            Assist = 287,
            Guillotine = 288,
            Mega_Drain = 289,
            Lucky_Chant = 290,
            Giga_Drain = 291,
            Petal_Dance = 292,
            Horn_Attack = 293,
            Stealth_Rock = 294,
            Horn_Drill = 295,
            Megahorn = 296,
            Dive = 297,
            Sludge = 298,
            Fling = 299,
            Sludge_Bomb = 300,
            Acid_Armor = 301,
            Memento = 302,
            Synthesis = 303,
            Bulk_Up = 304,
            Eruption = 305,
            Leaf_Blade = 306,
            Detect = 307,
            Reversal = 308,
            Flare_Blitz = 309,
            Magic_Coat = 310,
            Snore = 311,
            Encore = 312,
            Wring_Out = 313,
            Copycat = 314,
            Sweet_Kiss = 315,
            Iron_Head = 316,
            Metal_Sound = 317,
            Iron_Tail = 318,
            Metal_Burst = 319,
            Arm_Thrust = 320,
            Vital_Throw = 321,
            Fake_Out = 322,
            SmellingSalt = 323,
            Belly_Drum = 324,
            Force_Palm = 325,
            Seismic_Toss = 326,
            Endure = 327,
            Counter = 328,
            Comet_Punch = 329,
            Mach_Punch = 330,
            Bullet_Punch = 331,
            Vacuum_Wave = 332,
            Fire_Punch = 333,
            Sky_Uppercut = 334,
            Mega_Punch = 335,
            Double_Kick = 336,
            Rolling_Kick = 337,
            Jump_Kick = 338,
            High_Jump_Kick = 339,
            Mind_Reader = 340,
            Blaze_Kick = 341,
            Mega_Kick = 342,
            Triple_Kick = 343,
            Sunny_Day = 344,
            Sky_Attack = 345,
            Tailwind = 346,
            Psycho_Shift = 347,
            Smokescreen = 348,
            Dragon_Pulse = 349,
            Beat_Up = 350,
            Embargo = 351,
            Switcheroo = 352,
            Flatter = 353,
            Covet = 354,
            Taunt = 355,
            Growth = 356,
            Mimic = 357,
            Healing_Wish = 358,
            Doom_Desire = 359,
            Lovely_Kiss = 360,
            Fake_Tears = 361,
            Avalanche = 362,
            Mud_Shot = 363,
            Kinesis = 364,
            Miracle_Eye = 365,
            Role_Play = 366,
            Trick = 367,
            Dizzy_Punch = 368,
            Substitute = 369,
            Vice_Grip = 370,
            Crabhammer = 371,
            Sing = 372,
            Water_Spout = 373,
            Rock_Slide = 374,
            Mist_Ball = 375,
            Luster_Purge = 376,
            Power_Whip = 377,
            Energy_Ball = 378,
            Nature_Power = 379,
            Splash = 380,
            Return = 381,
            Power_Trick = 382,
            Bone_Rush = 383,
            Karate_Chop = 384,
            Revenge = 385,
            Submission = 386,
            Dynamic_Punch = 387,
            Snatch = 388,
            Grudge = 389,
            Lock0On = 390,
            Magnet_Bomb = 391,
            Barrier = 392,
            Heart_Swap = 393,
            Bone_Club = 394,
            Bonemerang = 395,
            Block = 396,
            Aromatherapy = 397,
            Pay_Day = 398,
            Hammer_Arm = 399,
            Meteor_Mash = 400,
            Transform = 401,
            Metronome = 402,
            Power_Swap = 403,
            Thief = 404,
            Milk_Drink = 405,
            Pain_Split = 406,
            Torment = 407,
            Slack_Off = 408,
            Camouflage = 409,
            Twineedle = 410,
            Aurora_Beam = 411,
            Octazooka = 412,
            Tickle = 413,
            Spike_Cannon = 414,
            Super_Fang = 415,
            Spore = 416,
            Feather_Dance = 417,
            Hyper_Fang = 418,
            Conversion_2 = 419,
            Conversion = 420,
            Sharpen = 421,
            Head_Smash = 422,
            Fly = 423,
            Skull_Bash = 424,
            Crush_Grip = 425,
            Flash_Cannon = 426,
            Rock_Wrecker = 427,
            Brave_Bird = 428,
            Ice_Ball = 429,
            Poison_Tail = 430,
            Seed_Flare = 431,
            Icicle_Spear = 432,
            Clamp = 433,
            Steel_Wing = 434,
            Sketch = 435,
            Teeter_Dance = 436,
            Frustration = 437,
            Defend_Order = 438,
            Heal_Order = 439,
            Attack_Order = 440,
            Focus_Punch = 441,
            Tail_Glow = 442,
            Needle_Arm = 443,
            Bug_Bite = 444,
            Pluck = 445,
            Weather_Ball = 446,
            Chatter = 447,
            Facade = 448,
            Lunar_Dance = 449,
            Dark_Void = 450,
            Cut = 451,
            Rock_Smash = 452,
            Volt_Tackle = 453,
            Wide_Slash = 454,
            Waterfall = 455,
            Rock_Climb = 456,
            Draco_Meteor = 457,
            Grass_Knot = 458,
            Defog = 459,
            Drain_Punch = 460,
            Secret_Power = 461,
            Surf = 462,
            Skill_Swap = 463,
            Present = 464,
            Trick_Room = 465,
            Struggle = 466,
            Overheat = 467,
            Brick_Break = 468,
            Strength = 469,
            Rare_Fossil = 470,
            Quick_Orb = 471,
            Foe0Hold_Orb = 472,
            Spurn_Orb = 473,
            Warp_Orb = 474,
            Petrify_Orb = 475,
            Smoke_Ball = 476,
            Totter_Orb = 477,
            Slumber_Orb = 478,
            Blast_Seed = 479,
            Geo_Pebble = 480,
            Gravelerock = 481,
            Golden_Fang = 482,
            Silver_Spike = 483,
            Frozen_Stick = 484,
            Iron_Thorn = 485,
            Corsola_Twig = 486,
            Sharp_Bone = 487,
            Cacnea_Spike = 488,
            Stick = 489,
            Tiny_Thorn = 490,
            Shiny = 491,
            PP0Zero_Trap = 493,
            Sludge_Trap = 494,
            Mud_Trap = 495,
            Toxic_Trap = 496,
            Explosion_Trap = 497,
            Flute = 498,
            Wonder_Tile = 499,
            RageCandyBar = 500,
            Sparkle = 502,
            Illusion = 503,
            Pink_Smoke = 504,
            Brown_Smoke = 505,
            Fire = 506,
            Animationless_AoE = 507,
            Animated_AoE = 508,
            Revive = 509,
            Elixir = 510,
            Potion = 511,
            Full_Heal = 512,
            Super_Potion = 513,
            Hyper_Potion = 514,
            Max_Potion = 515,
            Max_Elixir = 516,
            Full_Restore = 517,
            Rollcall_Orb = 518,
            All0Hit_Orb = 519,
            All0Mach_Orb = 520,
            Blowback_Orb = 521,
            Foe0Seal_Orb = 522,
            All0Aim_Orb = 523,
            Invisify_Orb = 524,
            Two0Edge = 525,
            Snowball = 526,
            Pounce_Orb = 529,
            Rebound_Orb = 530,
            Grassy_Terrain = 537,
            Shocker_Trap = 538,
            Spirit_Tag = 539,
            Shatter = 540,
            Antidote = 541,
            Parlyz_Heal = 542,
            Awakening = 543,
            Burn_Heal = 544,
            Ice_Heal = 545,
            FireFlareBlast = 546,
            FuckThisNoise = 547,
            Confide = 548,
            Petal_Blizzard = 549,
            Power0Up_Punch = 550,
            Chestnut_Trap = 551,
            Spike_Trap = 553,
            Warp_Trap = 555,
            Trip_Trap = 557,
            Seal_Trap = 558,
            Slow_Trap = 559,
            Spin_Trap = 560,
            Summon_Trap = 561,
            Grudge_Trap = 562,
            Feint_Attack = 563,
            Gust_Trap = 564,
            Infestation = 565,
            Fell_Stinger = 566,
            Belch = 567,
            Play_Nice = 568,
            Nuzzle = 569,
            Rototiller = 570,
            Venom_Drench = 571,
            Disarming_Voice = 572,
            Moonblast = 573,
            Titty_Sprinkles = 574,
            Icecream = 575,
            Party_Confetti = 576,
            Health_Orb = 577,
            Recovery_Orb = 578,
            Freezeover = 580,
            Nullify_Orb = 582,
            Pokeflute = 583,
            Stayaway_Orb = 584,
            Pierce_Orb = 585,
            Longtoss_Orb = 586,
            Shocker_Orb = 587,
            One0Shot_Orb = 588,
            All0Dodge_Orb = 589,
            Ultra_Ball = 590,
            Firah = 591,
            Tele = 592,
            Fun = 593,
            Drunk = 594,
            Pokeball = 595,
            Move_Spam = 596,
            Dead = 597,
            Sleep = 598,
            Stop = 599,
            Debug = 600,
            Hone_Claws = 601,
            Wide_Guard = 602,
            Guard_Split = 603,
            Power_Split = 604,
            Wonder_Room = 605,
            Psyshock = 606,
            Venoshock = 607,
            Autotomize = 608,
            Rage_Powder = 609,
            Telekinesis = 610,
            Magic_Room = 611,
            Smack_Down = 612,
            Storm_Throw = 613,
            Flame_Burst = 614,
            Sludge_Wave = 615,
            Quiver_Dance = 616,
            Heavy_Slam = 617,
            Synchronoise = 618,
            Electro_Ball = 619,
            Soak = 620,
            Flame_Charge = 621,
            Coil = 622,
            Low_Sweep = 623,
            Acid_Spray = 624,
            Foul_Play = 625,
            Simple_Beam = 626,
            Entrainment = 627,
            After_You = 628,
            Round = 629,
            Echoed_Voice = 630,
            Chip_Away = 631,
            Clear_Smog = 632,
            Stored_Power = 633,
            Quick_Guard = 634,
            Ally_Switch = 635,
            Scald = 636,
            Shell_Smash = 637,
            Heal_Pulse = 638,
            Hex = 639,
            Sky_Drop = 640,
            Shift_Gear = 641,
            Circle_Throw = 642,
            Incinerate = 643,
            Quash = 644,
            Acrobatics = 645,
            Reflect_Type = 646,
            Retaliate = 647,
            Final_Gambit = 648,
            Bestow = 649,
            Inferno = 650,
            Water_Pledge = 651,
            Fire_Pledge = 652,
            Grass_Pledge = 653,
            Volt_Switch = 654,
            Struggle_Bug = 655,
            Bulldoze = 656,
            Frost_Breath = 657,
            Dragon_Tail = 658,
            Work_Up = 659,
            Electroweb = 660,
            Wild_Charge = 661,
            Drill_Run = 662,
            Dual_Chop = 663,
            Heart_Stamp = 664,
            Horn_Leech = 665,
            Sacred_Sword = 666,
            Razor_Shell = 667,
            Heat_Crash = 668,
            Leaf_Tornado = 669,
            Steamroller = 670,
            Cotton_Guard = 671,
            Night_Daze = 672,
            Psystrike = 673,
            Tail_Slap = 674,
            Hurricane = 675,
            Head_Charge = 676,
            Gear_Grind = 677,
            Searing_Shot = 678,
            Techno_Blast = 679,
            Relic_Song = 680,
            Secret_Sword = 681,
            Glaciate = 682,
            Bolt_Strike = 683,
            Blue_Flare = 684,
            Fiery_Dance = 685,
            Freeze_Shock = 686,
            Ice_Burn = 687,
            Snarl = 688,
            Icicle_Crash = 689,
            V0Create = 690,
            Fusion_Flare = 691,
            Fusion_Bolt = 692,
            Oblivion_Wing = 693,
            Precipice_Blades = 694,
            Dazzling_Gleam = 695,
            Baby0Doll_Eyes = 696,
            Play_Rough = 697,
            Misty_Terrain = 698,
            Smelling_Salts = 700,
            Electric_Terrain = 701,
            Eerie_Impulse = 702,
            Magnetic_Flux = 703,
            Draining_Kiss = 704,
            Freeze0Dry = 705,
            Sticky_Web = 706,
            Phantom_Force = 707,
            Boomburst = 708,
            Fairy_Wind = 709,
            Spiky_Shield = 710,
            Origin_Pulse = 711,
            Dragon_Ascent = 712,
            Ion_Deluge = 713,
            Mystical_Fire = 714,
            //Boomburst = 715,
            Mat_Block = 716,
            Water_Shuriken = 717,
            Powder = 718,
            Noble_Roar = 719,
            Flower_Shield = 720,
            Parting_Shot = 721,
            Kings_Shield = 722,
            Aromatic_Mist = 723,
            Topsy0Turvy = 724,
            Electrify = 725,
            Parabolic_Charge = 726,
            Flying_Press = 727,
            Fairy_Lock = 728,
            Crafty_Shield = 729,
            Forests_Curse = 730,
            //Phantom_Force = 731,
            Trick0or0Treat = 732,
            Geomancy = 733,
            Lands_Wrath = 734,
            Diamond_Storm = 735,
            Hyperspace_Hole = 736,
            Steam_Eruption = 737,
            nya = 738,
            Gods_Wrath = 750,
            Speed_Swap = 801
        }

        public static string PokeName(int DexNum)
        {

            if (DexNum > 7000)
                DexNum -= 7000;

            try
            {
                return PokeFromNum[DexNum - 1];
            }
            catch
            {
                return PokeFromNum[PokeFromNum.Count() - 1];
            }
        }

        public static Image PokeSpriteFromDex(int DexNum)
        {

            string FormattedName = PokeName(DexNum).ToLower();
            FormattedName = FormattedName.Replace("♂", "-m");
            FormattedName = FormattedName.Replace("♀", "-f");
            FormattedName = FormattedName.Replace("’", "");
            FormattedName = FormattedName.Replace(" ", "-");
            FormattedName = FormattedName.Replace(":", "-");
            FormattedName = FormattedName.Replace(".", "");



            try
            {
                int i = 0;
                while (true)
                {
                    i++;
                    if ((i % 2) > 0)
                        DexNum = 7000000;
                    else if (i < 5)
                        DexNum = 1;
                    //Error after 4 retries
                    else
                        throw new WebException();
                    try
                    {
                        WebRequest request;

                        if (DexNum > 7000)
                        {
                            request = WebRequest.Create("https://img.pokemondb.net/sprites/sun-moon/dex/normal/" + FormattedName + "-alolan.png");
                        }
                        else
                        {
                            request = WebRequest.Create("https://img.pokemondb.net/artwork/" + FormattedName + ".jpg");
                        }

                        using (var response = request.GetResponse())
                        using (var stream = response.GetResponseStream())
                        {
                            return Image.FromStream(stream);
                        }
                    }
                    catch
                    {

                    }
                }
            }

            catch
            {
                return new Bitmap(1, 1);
            }
        }

        public enum PokémonType
        {
            None,
            Bug,
            Dark,
            Dragon,
            Electric,
            Fairy,
            Fighting,
            Fire,
            Flying,
            Ghost,
            Grass,
            Ground,
            Ice,
            Normal,
            Poison,
            Psychic,
            Rock,
            Steel,
            Water
        }

        public enum GrowthGroup
        {
            None = 0,
            Erratic = 1,
            Fast = 2,
            MediumFast = 3,
            MediumSlow = 4,
            Slow = 5,
            Fluctuating = 6
        }
    }
}
